[project]
name = "fastapi-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mohammed Algherbawi", email = "mohamed19992005@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.142.2",
    "pwdlib[argon2]>=0.3.1",
    "pyjwt>=2.15.1",
    "sqlmodel>=0.0.47",
]

[project.scripts]
fastapi-course = "fastapi_course:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
